### ISSUE TITLE
Booting does not proceed and freezes with the "Loading Initial ramdisk" message after selecting the SMDK kernel

### ISSUE THREAD

**Issue by qiaobaaa** [OpenMPDK/SMDK#10]
hi,I am an employee of Samsung R&D Institute China-Xian. Recently, I need to use SMDK software in researching cxl related projects . Install & update the kernel without any problems.
Guide said if booting does not proceed and freezes with the "Loading Initial ramdisk" message after selecting the SMDK kernel, reboot using the kernel you previously used, enter the command below, and retry SMDK kernel booting. 
$ cd /path/to/SMDK/lib/linux-5.18-rc3-smdk
$ sudo make modules_install -j 8
$ cd /lib/modules/{kernel_name}
$ sudo find . -name *.ko -exec strip --strip-unneeded {} +
$ cd /path/to/SMDK/lib/linux-5.18-rc3-smdk
$ sudo make install -j 8
$ sudo update-grub
After I did the above steps, the reboot still freezes at "Loading Initial ramdisk", is there any good solution, looking forward to your reply.

Server environment:
Linux smc-PowerEdge-R930 5.10.131 #1 SMP Tue Jul 19 18:15:52 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
smpboot: CPU0: Intel(R) Xeon(R) CPU E7-4809 v4 @ 2.10GHz (family: 0x6, model: 0x4f, stepping: 0x1)
              total        used        free      shared  buff/cache   available
Mem:          23988        1065       22309          23         613       22558
Swap:          2047           0        2047

**Comment by KyungsanKim** [comment]
Hi, sometime see the freeze when ramdisk is too big.
In fact, "sudo find . -name *.ko -exec strip --strip-unneeded {} +"  command is guided to make the ramdisk smaller.
If you still see the issue even after the command, 
why don't you remove some modules in the reference kernel config to make the ramdisk smaller, and retry ?

**Comment by KyungsanKim** [comment]
If you still see the freeze having done the command above,
I suggest you consider adjusting kernel config to fit your system being tested.
The reference kernel configs we provided us for CXL enabled system. 

https://github.com/OpenMPDK/SMDK/wiki/3.-User-Guide#311-installation
