### ISSUE TITLE
Linux Kernel Compilation failure because of the change in __GFP_BITS_SHIFT definition with smdk_v1.2 tag

### ISSUE THREAD

**Issue by vjonnal** [OpenMPDK/SMDK#12]
https://github.com/OpenMPDK/SMDK/blob/9ebacf0fa9ff0a0926ad0380346def548813228d/lib/linux-5.18-rc3-smdk/include/linux/gfp.h#L280

The check in the below line is failing because of the change in __GFP_BITS_SHIFT definition. https://github.com/OpenMPDK/SMDK/blob/9ebacf0fa9ff0a0926ad0380346def548813228d/lib/linux-5.18-rc3-smdk/lib/radix-tree.c#L1597

**Comment by KyungsanKim** [comment]
Hi, could you check and tell me if CONFIG_EXMEM is enabled ?

**Comment by vjonnal** [comment]
Hello,
    Thank you for your response.
Following are the details that you have asked.
1. kernel config
CONFIG_EXMEM=yes
CONFIG_PROVE_LOCKING=no
CONFIG_LOCK_STAT=no
CONFIG_DEBUG_LOCK_ALLOC=no
CONFIG_LOCKDEP=yes
2. OS Distro:
Ubuntu 21.10
3. System/CPU:
AMD EPYC 7452
4. Personal interest.

**Comment by KyungsanKim** [comment]
Hi, Thank you for the reply. 
As a workaround, configuring "CONFIG_EXMEM=yes and CONFIG_LOCKDEP=no" will disappear the build issue, we are preparing a patch , though.
By the way, is there a specific hack you want to do with the lockdep function?

**Comment by vjonnal** [comment]
Nothing specific with LOCKDEP, I removed the config and verified that the compilation issue is resolved. 
Just wanted to keep you informed.
Will wait for the patch. 
Thank you.

**Comment by KyungsanKim** [comment]
Thank you for informing us, Ravi Shankar.

Patch is updated : 
release - https://github.com/OpenMPDK/SMDK/releases/tag/smdk_v1.2.1
commit - https://github.com/OpenMPDK/SMDK/commit/2cd3b4b514c9095343037cce62f7db6492ad93a4

**Comment by vjonnal** [comment]
Verified that kernel compilation issue is solved with smdk_v1.2.1 tag.
Closing the issue.
