### ISSUE TITLE
Intelligent Tiering Engine

### ISSUE THREAD

**Issue by insoulity** [OpenMPDK/SMDK#13]
Could you specify where "the Intelligent Tiering Engine" is implemented in SMDK?

**Comment by KyungsanKim** [comment]
It is working on userspace library over OS aid memory partition.

**Comment by insoulity** [comment]
Thanks for the response. Does that mean it is not implemented in any of the codes in this repository?

**Comment by insoulity** [comment]
I have closed this by mistake and reopened for the question above.

**Comment by KyungsanKim** [comment]
Nope, Intelligent Tiering Engine is implemented across SMDK allocator library and kernel.
