### ISSUE TITLE
SMDK under Qemu CXL2.0 emulation

### ISSUE THREAD

**Issue by gokwok** [OpenMPDK/SMDK#15]
Hi,

Nowadays, I'm glad to look at QEMU 7.2.50 supports the CXL2.0 emulation in:
https://www.qemu.org/docs/master/system/devices/cxl.html

And the latest dev branch for qemu cxl is enable to support cxl-type3 volatile memory:
https://gitlab.com/jic23/qemu/-/tree/cxl-2022-11-17

Now can SMDK tested/evaluated with QEMU now? If so, how to set it up?

Thanks in advance.

**Comment by KyungsanKim** [comment]
Hi, 
SMDK v1.3 includes QEMU v7.1.0. 
We checked the version of QEMU also supports type3 enumeration. 

Please refer to guide below for using QEMU with SMDK.
https://github.com/OpenMPDK/SMDK/wiki/4.-Kernel#426-qemu

**Comment by gokwok** [comment]
> Hi, SMDK v1.3 includes QEMU v7.1.0. We checked the version of QEMU also supports type3 enumeration.
> 
> Please refer to guide below for using QEMU with SMDK. https://github.com/OpenMPDK/SMDK/wiki/4.-Kernel#426-qemu

Thank you for offering guide!
But I tried with QEMU v7.1.0 in SMDK v1.3. But when I start qemu by guide, the SMDK kernel seems has something wrong:

```
[    1.165645] CXL: failed to add cxl meminfo
[    1.166162] CXL: failed to add cxl meminfo
[    1.167074] cxl_pci 0000:0d:00.0: vgaarb: pci_notify
[    1.167078] cxl_pci 0000:0d:00.0: runtime IRQ mapping not provided by arch
[    1.167155] CXL: register cxl dvsec ranges
[    1.168614] cxl_pci 0000:0d:00.0: vgaarb: pci_nofify
[    1.168628] CXL: register cxl cfmws ranges
[    1.169141] CXL: Failed to add cxl meminfo
[    1.169655] CXL: Failed to add cxl info with cedt.cfmws
[    1.170344] cxl_acpi: probe of ACPI0017:00 failed with error -22
```

And I also can't find EXMEM Zone in buddyinfo:
```shell
[[Buddy Info]]
Node 0, zone      DMA      0      0      0      0      0      0      0      0      1      1      3
Node 0, zone    DMA32      6      6      4      6      5      3      4      5      3      5    482
Node 0, zone   Normal      917     344      121     38     6     2      3      1      2      3  1469
Node 1, zone   Normal      357     157      64       22     5     2      1      1      1      1  1985
```

This start of QEMU command is shown below:
```shell
sudo ${QEMU_SYSTEM_BINARY} \
    -smp 6 \
    -numa node,cpus=0-2,memdev=mem0,nodeid=0 \
    -object memory-backend-ram,id=mem0,size=8G \
    -numa node,cpus=3-5,memdev=mem1,nodeid=1 \
    -object memory-backend-ram,id=mem1,size=8G \
    -kernel ${BZIMAGE_PATH} \
    -drive file=${IMAGE_PATH},index=0,media=disk,format=raw \
    -enable-kvm \
    -monitor telnet::${MONITOR_PORT},server,nowait \
    -serial mon:stdio \
    -nographic \
    -append "root=/dev/sda2 rw console=ttyS0 nokaslr memblock=debug loglevel=7" \
    -m 16G,slots=4,maxmem=32G \
    -machine q35,cxl=on \
    -M cxl-fmw.0.targets.0=cxl.1,cxl-fmw.0.size=4G \
    -device pxb-cxl,bus_nr=12,bus=pcie.0,id=cxl.1 \
    -device cxl-rp,port=0,bus=cxl.1,id=root_port13,chassis=0,slot=2 \
    -object memory-backend-file,id=cxl-mem1,share=on,mem-path=/tmp/cxltest.raw,size=256M \
    -object memory-backend-file,id=cxl-lsa1,share=on,mem-path=/tmp/lsa.raw,size=256M \
    -device cxl-type3,bus=root_port13,memdev=cxl-mem1,lsa=cxl-lsa1,id=cxl-mem0 \
    ${NET_OPTION}
```
What's wrong?

**Comment by KyungsanKim** [comment]
We have experienced a similar phenomenon on QEMU 7.1.10 using both vanilla and SMDK kernel.  
Our result was type 3 device on the QEMU version can be emulated as a NUMA node, but actual load/store on the NUMA page caused kernel fault. 
We are checking if the phenomenon is resolved on the lastest QEMU, 7.2.50. Will update you.

**Comment by gokwok** [comment]
> We have experienced a similar phenomenon on QEMU 7.1.10 using both vanilla and SMDK kernel. Our result was type 3 device on the QEMU version can be emulated as a NUMA node, but actual load/store on the NUMA page caused kernel fault. We are checking if the phenomenon is resolved on the lastest QEMU, 7.2.50. Will update you.

Thank you for your help!

**Comment by KyungsanKim** [comment]
We have tested SMDK kernel using the lastest QEMU, v7.2.50. 
In fact, a patch set needs to be applied on SMDK kernel to show EXMEM zone.
QEMU v7.10 raised "2042 Illegal instruction" when we do load/store operation on a page out of the memory-node emulated.
QEMU v7.2.50 does not raised the error, but "miscompare error" is happending when we run the testcase that stores and then compares loaded data. 

In case of vanilla kernel, it shows an error to emulated type 3 device as memory-node. 

Thus, unfortunately, we think there is some limitation in QEMU to fully support type3 device emulation.
I'm sorry that we did not further analyzed QEMU internal. 

For the QEMU test, we have used  "./run_cxl_emu_gui.sh" script in our guide. 
Please let us know if you want to reproduce the test procedure we performed.
FYI, One of our partner had experiend the similar error, and now they are using a real CXL system and device,,

**Comment by gokwok** [comment]
> We have tested SMDK kernel using the lastest QEMU, v7.2.50. In fact, a patch set needs to be applied on SMDK kernel to show EXMEM zone. QEMU v7.10 raised "2042 Illegal instruction" when we do load/store operation on a page out of the memory-node emulated. QEMU v7.2.50 does not raised the error, but "miscompare error" is happending when we run the testcase that stores and then compares loaded data.
> 
> In case of vanilla kernel, it shows an error to emulated type 3 device as memory-node.
> 
> Thus, unfortunately, I'm sorry to tell we think there is some limitation in QEMU to fully support type3 device emulation. I'm sorry that we did not further analyzed QEMU internal.
> 
> For the QEMU test, we have used "./run_cxl_emu_gui.sh" script in our guide. Please let us know if you want to reproduce the test procedure we performed all the way.

What's the patch set needs to be applies on SMDK kernel to show EXMEM zone?
And can I get the test procedure you performed?
Thank you very much!

**Comment by KyungsanKim** [comment]
Could you please let us know the purpose of your research to ks0204.kim@samsung.com for further help?

**Comment by gokwok** [comment]
> Could you please let us know the purpose of your research to [ks0204.kim@samsung.com](mailto:ks0204.kim@samsung.com) for further help?

I‘m doing some research works for college. Thank you for your help!

**Comment by Second222None** [comment]
Hi, 
  Any available solutions?
