### ISSUE TITLE
Does SMDK Support Other CXL Memory Devices apart from Samsung CXL Memory Expander??

### ISSUE THREAD

**Issue by pixiesunky** [OpenMPDK/SMDK#16]
The SMDK looks quite promising and is great to have a real test. But due to some reasons, I don't have Samsung CXL memory Expander currently. I am wondering if the SMDK can support other CXL Memory Device including both Compatible and Optimization Paths 

Many Thanks

**Comment by KyungsanKim** [comment]
Hello, Sure it is. 
I believe it is usual that a single software works on multiple vendors' devices. 
Also, a single device can be operated by a multiple softwares. criss-cross. 

However, there will be some vendor-specific optimization features.

**Comment by pixiesunky** [comment]
Many thanks for the confirmation!
