### ISSUE TITLE
CXL Specification version and Linux kernel version

### ISSUE THREAD

**Issue by PeterDLUT** [OpenMPDK/SMDK#22]
Hi, I' d like to ask which version of the CXL specification does SMDK support? Because wiki doesn' t mention supporting CXL 2.0 features such as switches and hot-plugging. Or SMDK doesn' t care about the version of CXL?
Also, I noticed that the SMDK includes Linux 6.0 kernel. Is it compatible with other Linux versions with CXL drivers?
Many thanks.

**Comment by KyungsanKim** [comment]
Hi, at the moment, SMDK targets CXLs spec v1.1 and v2.0. 
Along with progress of CXL products and infrastructures, we have plan to version up functionalities. 

Right now, SMDK concerns logical memory on/offline of CXL memory. 
For physical hot-add/removal and data consistency, we will investigate more support needed. 
Preparing CXL pooling stage, we have been enabling some memory tiering features such as using CXL memory as 
OS level swap and cache. 

Right now, SMDK kernel is customized, and next release (v1.5) will use baseline v6.4 
There are some gaps between vanilla kernel and SMDK kernel now.
We are investigating migration and upstream plan to align with vanilla kernel eventually.
