### ISSUE TITLE
How to use SMDK to request CXL memory in kernel space?

### ISSUE THREAD

**Issue by badseed-hub** [OpenMPDK/SMDK#27]
Hi~~ In user space, we can use "s_malloc" to request CXL memory; so if I'm in kernel space, what interface should I use to request CXL memory? 
Thanks a lot~~

**Comment by KyungsanKim** [comment]
Hi, Thank you for the meaningful question 👍 
I also think the problem has to be addressed:  Identifying CXL memory in kernelspace.

Until v1.5.1, SMDK used to provide an new explicit flag for kernelspace,  __GFP_EXMEM.
From SMDK v2.0, finds CXL memory using __GFP_MOVABLE && memory-node nodelist.
Both are not perfact, but SMDK RFC.

At the moment, I believe we all need to find an sophisticated solution with a consensus. 

Happy new year! :)
