### ISSUE TITLE
Minor Typo in Wiki

### ISSUE THREAD

**Issue by gjujinkim96** [OpenMPDK/SMDK#29]
Location: [https://github.com/OpenMPDK/SMDK/wiki/7.-Experiment-Results#741-methodology](https://github.com/OpenMPDK/SMDK/wiki/7.-Experiment-Results#741-methodology)

Description: There is a minor typo in the description of "Cuse_bw" in the wiki. Attached is an image with a red circle indicating the error.

Incorrect Text: "Cuse_bw = in-use BW of DDR DRAM"

Corrected Text: "Cuse_bw = in-use BW of CXL RAM"

Attachment:
<img width="800" alt="typo_wiki" src="https://github.com/OpenMPDK/SMDK/assets/22863750/e3c0125e-9dcf-47ab-9aa4-5cc3117c6933">

**Comment by junhyeok-im** [comment]
hello gjujinkim96,
I really appreciate your feedback and comment, and I have modified it as per your suggestion.

Thank you!

**Comment by junhyeok-im** [comment]
I am going to close this issue, thanks gjujinkim96 once again for your comment.
