### ISSUE TITLE
Trying out SMDK on a VM

### ISSUE THREAD

**Issue by arter97** [OpenMPDK/SMDK#5]
Hi,

I'm currently trying to setup and use SMDK. As I don't have a CXL-capable CPU and a CXL device, I'm trying under a virtual machine using QEMU (w/ CXL modifications).

This repository includes QEMU, so I assumed that the SMDK was tested with QEMU. However, I was not able to get SMDK working under QEMU, even after forcefully creating the SRAT ACPI table under the virtual machine.
I noticed that the QEMU helper scripts under this repository don't include any CXL device declaration such as "-device cxl-type3".

Is SMDK tested/evaluated under QEMU?
If so, how can we set it up?
If not, what is the purpose of including the QEMU source code and the QEMU helper scripts?

Thanks in advance.

**Comment by KyungsanKim** [comment]
Hello, thank you for your interest on SMDK and CXL Device.
The purpose of QEMU TCs in SMDK is to run QEMU on SMDK kernel.
As you told, right now QEMU does not support cxl device type.  
We are using QEMU on SMDK kernel not to emulate CXL device, but to simulate other Linux subsystems.
