### ISSUE TITLE
About the timeframe for upstreaming patches in linux-5.18-rc3-smdk

### ISSUE THREAD

**Issue by cyliustack** [OpenMPDK/SMDK#6]
Hi all,
do you have any timeframe for upstreaming patches in linux-5.18-rc3-smdk?

**Comment by KyungsanKim** [comment]
Hi. Thank you for interest on SMDK.
Yes, eventual goal is to upstream. 
However, considering OS nature, many consensus  and maturity in technology should come first, we believe. 
So, for the timing being, we are separately providing a SMDK linux fork, https://github.com/openMPDK/SMDK-linux-cxl 
On 5/17, SMDK is merged on v5.18-rc7
