### ISSUE TITLE
cxl_pci.ko driver failed to load

### ISSUE THREAD

**Issue by jacabay** [OpenMPDK/SMDK#7]
I built and installed the SMDK kernel **5.18-rc3-smdk** under Ubuntu 22.04. I could see my CXL device in the lspci output and recognized as ExMem zone in the buddyinfo output as shown below.
 
![image](https://user-images.githubusercontent.com/80230679/169444695-809cb49d-6f0c-4a68-8442-a5957814132b.png)

![image](https://user-images.githubusercontent.com/80230679/169444416-e00009d3-e80d-4665-9835-69fe3ff4824f.png)

But when I checked the CXL drivers, only cxl_core was loaded.

![image](https://user-images.githubusercontent.com/80230679/169444986-8db08c9d-9629-4082-8be7-ce122a0a01da.png)

When I tried to load driver, cxl_pci.ko, I got below error.

![image](https://user-images.githubusercontent.com/80230679/169445160-d2f18562-3e81-487a-b695-83efe3f94677.png)

Could you help decode the error messages?
If cxl_pci.ko is not loaded, how does it affect the CXL operation and testing?

**Comment by wj28lees** [comment]
First of all, since the page is registered in the ExMem zone, it seems possible to test the CXL memory.

However, It is strange that pages are registered in the ExMem zone when the cxl_pci module is not loaded, because the CXL memory registration is performed in cxl_pci.ko.

Can you provide dmesg full log for the above situation? Then I think a more detailed analysis is possible.

**Comment by wj28lees** [comment]
> Can you provide your email address for sending the dmesg log just to you?

It's wj28.lee@samsung.com

**Comment by jacabay** [comment]
thank you! I've sent you the dmesg log via email.

**Comment by KyungsanKim** [comment]
Thank you for sharing the experiment result.
Your feedback is valuable us to make SMDK robustness.
In a few days, we will update SMDK kernel repo, https://github.com/OpenMPDK/SMDK-linux-cxl, that clones tovalds for the error handling logic.
Furthermore, SMDK repo will update the logic on next offcial release.
Please fee free to contact us for any upcoming inquery.
