### ISSUE TITLE
Ethernet Adapter degraded after booted into SMDK kernel

### ISSUE THREAD

**Issue by jacabay** [OpenMPDK/SMDK#8]
The network adapter link on my system became disabled (link down) after I booted into the SMDK kernels built with either SMDK 1.0 (l**inux-5.17-rc5-smdk**)  in Ubuntu 21.10 or SMDK 1.1 (**linux-5.18.rc3-smdk**) in Ubuntu 22.04. The network link would be normal and working if I booted into the generic kernels. What can I do to fix this issue?

**Comment by KyungsanKim** [comment]
Hi jacabay.
You probably use the reference config files in the repo lib/os_configs, config-amd-ubuntu-linux-5.17-rc5-smdk add config-amd-ubuntu-linux-5.18-rc3-smdk. The configs may disable your NIC drviers. 

Referring to the config file of your generic kernels at /boot/config-***, you needs to enable configs for your NIC.
